databases:
  - name: restoapp-db
    plan: free
    databaseName: restoapp
    user: restoapp

services:
  - type: web
    name: restoapp
    plan: free
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.6"
      - key: DATABASE_URL
        fromDatabase:
          name: restoapp-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "0"
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: "https://restoapp.onrender.com"
